import { captureWindow } from './capture-window';
import {
  test,
  expect,
  _electron as electron,
  type ElectronApplication,
  type Page,
} from '@playwright/test';
import { createServer, type ServerResponse } from 'node:http';
import { createRequire } from 'node:module';
import { mkdirSync, mkdtempSync, readFileSync, renameSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { DatabaseSync } from 'node:sqlite';
const require = createRequire(import.meta.url);
const key = 'P03-FAKE-TEST-KEY-NOT-A-REAL-CREDENTIAL';
async function fixture() {
  let imageReply = 'red';
  let wait = false;
  let active: ServerResponse | null = null;
  const requests: { body: Record<string, unknown>; authorization: string | undefined }[] = [];
  const server = createServer((request, response) => {
    if (request.method !== 'POST') {
      response.writeHead(405);
      response.end();
      return;
    }
    let raw = '';
    request.on('data', (chunk) => (raw += chunk));
    request.on('end', () => {
      const body = JSON.parse(raw);
      requests.push({ body, authorization: request.headers.authorization });
      response.writeHead(200, { 'content-type': 'text/event-stream' });
      if (wait) {
        active = response;
        response.write(': waiting\n\n');
        return;
      }
      const content = body.messages[0].content;
      const answer = Array.isArray(content)
        ? imageReply
        : content === 'Reply with only OK.'
          ? 'OK'
          : JSON.stringify({
              document: '# Generated by ' + body.model,
              suggestions: 'Layout advice',
              rationale: 'Evidence-based',
            });
      response.end(
        'data: ' +
          JSON.stringify({
            choices: [{ index: 0, delta: { content: answer }, finish_reason: 'stop' }],
          }) +
          '\n\ndata: [DONE]\n\n',
      );
    });
  });
  await new Promise<void>((resolve) => server.listen(0, '127.0.0.1', resolve));
  const baseUrl = `http://127.0.0.1:${(server.address() as import('node:net').AddressInfo).port}/v1`;
  mkdirSync(resolve('.test-data'), { recursive: true });
  const directory = mkdtempSync(resolve('.test-data/p03-'));
  async function launch(data = directory) {
    const env: Record<string, string> = {
      ...Object.fromEntries(
        Object.entries(process.env).filter((e): e is [string, string] => e[1] !== undefined),
      ),
      CAREER_TEST_MODE: '1',
      CAREER_TEST_DATA: data,
    };
    delete env.ELECTRON_RUN_AS_NODE;
    delete env.CAREER_DEV_URL;
    const app = await electron.launch({ executablePath: require('electron'), args: ['.'], env });
    const page = await app.firstWindow();
    await expect(page.getByRole('navigation', { name: '求职工具' })).toBeVisible();
    return { app, page };
  }
  return {
    launch,
    baseUrl,
    directory,
    requests,
    setImage: (value: string) => (imageReply = value),
    setWait: (value: boolean) => (wait = value),
    close: async () => {
      active?.destroy();
      await new Promise<void>((resolve) => {
        server.close(() => resolve());
        server.closeAllConnections();
      });
    },
  };
}
async function addProvider(page: Page, name: string, baseUrl: string, apiKey = key) {
  await page.getByRole('button', { name: '添加供应商', exact: true }).click();
  await page.getByLabel('供应商名称', { exact: true }).fill(name);
  await page.getByLabel('Base URL', { exact: true }).fill(baseUrl);
  await page.getByLabel('API Key', { exact: true }).fill(apiKey);
  await page.getByRole('button', { name: '保存供应商', exact: true }).click();
  await expect(page.getByRole('button', { name: `管理 ${name}`, exact: true })).toBeVisible();
  await page.getByRole('button', { name: `管理 ${name}`, exact: true }).click();
}
async function addModel(page: Page, id: string, name: string, advanced = false) {
  await page.getByRole('button', { name: '添加模型', exact: true }).click();
  await page.getByLabel('模型 ID', { exact: true }).fill(id);
  await page.getByLabel('模型显示名称', { exact: true }).fill(name);
  if (advanced) {
    await page.getByLabel('图片能力', { exact: true }).selectOption('supported');
    await page.getByLabel('支持 temperature', { exact: true }).check();
    await page.getByLabel('温度 · 模型默认', { exact: true }).fill('0.6');
    await page.getByLabel('支持 max_completion_tokens', { exact: true }).check();
    await page.getByLabel('输出上限 · 模型默认', { exact: true }).fill('4096');
  }
  await page.getByRole('button', { name: '保存模型', exact: true }).click();
  await expect(page.getByRole('button', { name: `编辑模型 ${name}`, exact: true })).toBeVisible();
}
async function openSettings(page: Page) {
  await page.getByRole('button', { name: '应用设置', exact: true }).click();
}
async function closeSettings(page: Page) {
  await page.getByRole('button', { name: '完成', exact: true }).click();
}

test('multiple suppliers, per-page models, override precedence, immutable snapshots and batch deletion', async ({}, testInfo) => {
  const f = await fixture();
  let app: ElectronApplication | undefined;
  try {
    let loaded = await f.launch();
    app = loaded.app;
    let page = loaded.page;
    await openSettings(page);
    await addProvider(page, 'Alpha', f.baseUrl);
    await addModel(page, 'alpha', 'Writer', true);
    await addModel(page, 'alpha-lite', 'Lite');
    await addProvider(page, 'Beta', f.baseUrl, 'FAKE-BETA-KEY');
    await addModel(page, 'beta', 'Reviewer');
    expect(f.requests).toHaveLength(0);
    await closeSettings(page);
    await page
      .getByRole('combobox', { name: '本页模型' })
      .selectOption({ label: 'Writer / Alpha' });
    await page.getByRole('button', { name: '调整', exact: true }).click();
    await page.getByLabel('温度 · 本页覆盖', { exact: true }).fill('0.2');
    await page.getByRole('button', { name: '保存本页参数', exact: true }).click();
    await page.getByRole('button', { name: '撰写求职信', exact: true }).click();
    await page
      .getByRole('combobox', { name: '本页模型' })
      .selectOption({ label: 'Reviewer / Beta' });
    await page.locator('#user-prompt').fill('LETTER-PRIVATE');
    await page.getByRole('button', { name: '设计简历', exact: true }).click();
    await page.locator('#user-prompt').fill('Resume facts');
    await page.getByRole('button', { name: '生成简历', exact: true }).click();
    await expect(page.getByRole('dialog')).toContainText('"temperature":0.2');
    await page.getByRole('button', { name: '确认发送并生成', exact: true }).click();
    await expect(page.getByRole('region', { name: '简历生成状态' })).toContainText(
      '已保存正式版本 V1',
    );
    expect(f.requests[0].body.temperature).toBe(0.2);
    expect(f.requests[0].body.max_completion_tokens).toBe(4096);
    expect(f.requests[0].body.model).toBe('alpha');
    expect(f.requests[0].authorization).toBe(`Bearer ${key}`);
    expect(JSON.stringify(f.requests[0].body)).not.toContain('LETTER-PRIVATE');
    await app.close();
    app = undefined;
    loaded = await f.launch();
    app = loaded.app;
    page = loaded.page;
    await expect(
      page.getByRole('combobox', { name: '本页模型' }).locator('option:checked'),
    ).toHaveText('Writer / Alpha');
    await expect(page.locator('.page-parameter-summary')).toContainText('"temperature":0.2');
    await page.getByRole('button', { name: '撰写求职信', exact: true }).click();
    await expect(
      page.getByRole('combobox', { name: '本页模型' }).locator('option:checked'),
    ).toHaveText('Reviewer / Beta');
    await expect(page.locator('#user-prompt')).toHaveValue('LETTER-PRIVATE');
    await openSettings(page);
    await page.getByRole('button', { name: '管理 Alpha', exact: true }).click();
    await page.getByRole('button', { name: '编辑模型 Writer', exact: true }).click();
    await expect(page.getByLabel('温度 · 模型默认', { exact: true })).toHaveValue('0.6');
    await page.getByLabel('模型显示名称', { exact: true }).fill('Writer renamed');
    await page.getByRole('button', { name: '保存模型', exact: true }).click();
    await page.getByRole('checkbox', { name: '选择模型 Lite', exact: true }).check();
    await page.getByRole('checkbox', { name: '选择模型 Writer renamed', exact: true }).check();
    await page.getByRole('button', { name: '删除所选模型（2）', exact: true }).click();
    await expect(page.getByRole('region', { name: '删除影响确认' })).toContainText('设计简历');
    await page.getByRole('button', { name: '取消', exact: true }).click();
    await expect(
      page.getByRole('button', { name: '编辑模型 Writer renamed', exact: true }),
    ).toBeVisible();
    await page.getByRole('button', { name: '删除所选模型（2）', exact: true }).click();
    await page.getByRole('button', { name: '确认删除所选配置', exact: true }).click();
    await expect(page.getByRole('dialog')).toContainText('草稿和历史版本保持不变');
    await page.getByRole('checkbox', { name: '全选供应商', exact: true }).check();
    await page.getByRole('button', { name: '删除所选供应商（2）', exact: true }).click();
    await expect(page.getByRole('region', { name: '删除影响确认' })).toContainText('撰写求职信');
    await page.getByRole('button', { name: '确认删除所选配置', exact: true }).click();
    await closeSettings(page);
    await expect(page.getByRole('combobox', { name: '本页模型' })).toHaveValue('');
    await expect(page.locator('#user-prompt')).toHaveValue('LETTER-PRIVATE');
    await page.getByRole('button', { name: '设计简历', exact: true }).click();
    await expect(page.getByRole('combobox', { name: '本页模型' })).toHaveValue('');
    await page.getByRole('button', { name: '本页记录', exact: true }).click();
    await page.getByRole('button', { name: /^V1/ }).click();
    await expect(page.locator('.version-detail')).toContainText('Generated by alpha');
    await page.keyboard.press('Escape');
  } finally {
    await app?.close();
    await f.close();
  }
});

test('text and image probes require consent, distinguish manual flags, expire after edits and cancel safely', async ({}, testInfo) => {
  const f = await fixture();
  let app: ElectronApplication | undefined;
  try {
    const loaded = await f.launch();
    app = loaded.app;
    const page = loaded.page;
    await openSettings(page);
    await addProvider(page, 'Probes', f.baseUrl);
    await addModel(page, 'vision', 'Vision', true);
    await page.getByRole('button', { name: '测试图片 · Vision', exact: true }).click();
    await expect(page.getByRole('region', { name: '测试发送确认' })).toContainText(
      '32×32 红色 PNG',
    );
    expect(f.requests).toHaveLength(0);
    await page.getByRole('button', { name: '确认发送测试', exact: true }).click();
    await expect(page.locator('.test-records')).toContainText('图片 · 已验证通过');
    const imageContent = (
      f.requests[0].body.messages as { content: { type: string; image_url?: { url: string } }[] }[]
    )[0].content;
    expect(imageContent[1].image_url?.url).toMatch(/^data:image\/png;base64,/);
    expect(f.requests[0].body.temperature).toBe(0.6);
    expect(f.requests[0].body.max_completion_tokens).toBe(4096);
    await page.getByRole('button', { name: '测试模型连通性 · Vision', exact: true }).click();
    await page.getByRole('button', { name: '确认发送测试', exact: true }).click();
    await expect(page.locator('.test-records')).toContainText('文本 · 已验证通过');
    await page.getByRole('button', { name: '编辑模型 Vision', exact: true }).click();
    await page.getByLabel('温度 · 模型默认', { exact: true }).fill('0.7');
    await page.getByRole('button', { name: '保存模型', exact: true }).click();
    await expect(page.locator('.test-records')).toContainText('已过期');
    f.setImage('blue');
    await page.getByRole('button', { name: '测试图片 · Vision', exact: true }).click();
    await page.getByRole('button', { name: '确认发送测试', exact: true }).click();
    await expect(page.locator('.test-records')).toContainText('图片 · 未通过');
    await expect(page.locator('.capability-tags')).toContainText('图片 · 手动标记支持');
    f.setWait(true);
    await page.getByRole('button', { name: '测试模型连通性 · Vision', exact: true }).click();
    await page.getByRole('button', { name: '确认发送测试', exact: true }).click();
    await expect(page.getByRole('button', { name: '取消测试', exact: true })).toBeVisible();
    await page.getByRole('button', { name: '取消测试', exact: true }).click();
    await expect(page.locator('.test-records')).toContainText('文本 · 未通过');
    await expect(page.locator('.test-records')).toContainText('已取消');
    await page.getByRole('button', { name: '编辑供应商 Probes', exact: true }).click();
    await expect(page.getByLabel('API Key', { exact: true })).toHaveValue('');
    await page.getByRole('button', { name: '取消编辑并返回列表', exact: true }).click();
    await page.getByRole('button', { name: '管理 Probes', exact: true }).scrollIntoViewIfNeeded();
    await captureWindow(app, testInfo.outputPath('p03-model-manager.png'));
  } finally {
    await app?.close();
    await f.close();
  }
});

test('a real P02 encrypted connection migrates on launch and stays deleted after restart', async () => {
  const f = await fixture();
  let app: ElectronApplication | undefined;
  try {
    const warm = await f.launch();
    app = warm.app;
    const encrypted = await app.evaluate(
      ({ safeStorage }, value) => Array.from(safeStorage.encryptString(value)),
      key,
    );
    await app.close();
    app = undefined;
    // Keep Electron's encryption profile; only replace the test database with a legacy schema.
    // Moving an encrypted key to another profile tests key portability, not an in-place upgrade.
    const migrated = f.directory;
    renameSync(join(migrated, 'workspace.sqlite'), join(migrated, 'before-legacy-fixture.sqlite'));
    const db = new DatabaseSync(join(migrated, 'workspace.sqlite'));
    db.exec(
      'CREATE TABLE ai_connection(id INTEGER PRIMARY KEY,metadata TEXT NOT NULL,encrypted_key BLOB NOT NULL); CREATE TABLE drafts(id TEXT PRIMARY KEY,payload TEXT NOT NULL); CREATE TABLE resume_versions(number INTEGER PRIMARY KEY AUTOINCREMENT,run_id TEXT UNIQUE NOT NULL,payload TEXT NOT NULL);',
    );
    const old = {
      providerName: 'Migrated supplier',
      baseUrl: f.baseUrl,
      endpoint: f.baseUrl + '/chat/completions',
      modelId: 'legacy-model',
      modelName: 'Legacy model',
      protocol: 'chat-completions',
      hasKey: true,
      revision: 'legacy-revision',
    };
    db.prepare('INSERT INTO ai_connection VALUES (1,?,?)').run(
      JSON.stringify(old),
      Buffer.from(encrypted),
    );
    const draft = {
      prompt: 'P02 original experiences',
      systemPrompt: 'Career Advisor',
      document: '# P02 existing draft',
      refinement: '',
      links: '',
      updatedAt: null,
    };
    db.prepare('INSERT INTO drafts VALUES (?,?)').run('resume', JSON.stringify(draft));
    db.prepare('INSERT INTO resume_versions(run_id,payload) VALUES (?,?)').run(
      'legacy-run',
      JSON.stringify({
        runId: 'legacy-run',
        createdAt: '2026-09-15T00:00:00Z',
        connection: old,
        input: { prompt: draft.prompt, systemPrompt: draft.systemPrompt, document: '' },
        document: '# Historical P02',
        suggestions: 'Layout',
        rationale: 'Evidence',
      }),
    );
    db.close();
    let loaded = await f.launch(migrated);
    app = loaded.app;
    let page = loaded.page;
    await expect(
      page.getByRole('combobox', { name: '本页模型' }).locator('option:checked'),
    ).toHaveText('Legacy model / Migrated supplier');
    await expect(page.locator('#user-prompt')).toHaveValue('P02 original experiences');
    await openSettings(page);
    await page.getByRole('button', { name: '测试模型连通性 · Legacy model', exact: true }).click();
    await page.getByRole('button', { name: '确认发送测试', exact: true }).click();
    await expect(page.getByRole('dialog')).toContainText('文本流式测试通过');
    await expect(page.locator('.test-records')).toContainText('文本 · 已验证通过');
    expect(f.requests[0].authorization).toBe(`Bearer ${key}`);
    await page.getByRole('button', { name: '删除供应商 Migrated supplier', exact: true }).click();
    await page.getByRole('button', { name: '确认删除所选配置', exact: true }).click();
    await closeSettings(page);
    await app.close();
    app = undefined;
    loaded = await f.launch(migrated);
    app = loaded.app;
    page = loaded.page;
    await expect(page.getByRole('combobox', { name: '本页模型' })).toHaveValue('');
    await openSettings(page);
    await expect(page.getByRole('dialog')).toContainText('还没有供应商');
    await closeSettings(page);
    await page.getByRole('button', { name: '本页记录', exact: true }).click();
    await page.getByRole('button', { name: /^V1/ }).click();
    await expect(page.locator('.version-detail')).toContainText('Historical P02');
    await page.keyboard.press('Escape');
    await app.close();
    app = undefined;
    expect(readFileSync(join(migrated, 'workspace.sqlite')).includes(Buffer.from(key))).toBe(false);
  } finally {
    await app?.close();
    await f.close();
  }
});
